project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar: 
    left:
      - text: About
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Résumé
        href: resume.qmd
      # - text: Blog
      #   href: blog.qmd

        
    right:
      - icon: github
        href: https://github.com/JMurb
      - icon: linkedin
        href: https://www.linkedin.com/in/jmurb

format:
  html:
    theme: cosmo
    toc: true
    css: style/styles.scss


editor: visual

