project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar: 
    left:
      - text: "-"
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Résumé
        href: resume.qmd
      - text: Blog
        href: blog.qmd
      - text: About
        href: index.qmd
        
    right:
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    toc: true
    css: style/styles.scss


editor: visual

